name: "Caching Demo"
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: npm cache directory
        id: npm-cache-dir
        run: |
          echo "npm cache dir: $(npm config get cache)"
          echo "cache_dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: npm cache
        id: npm-cache
        uses: actions/cache@v6
        with:
          key: ganesh-npm-cache
          path: ${{ steps.npm-cache-dir.outputs.cache_dir }}
          
      - name: Cache status
        run: |
          echo "Status: ${{ steps.npm-cache.outputs.cache-hit }}"

      - name: Install node modules
        run: |
          cd node-app && npm ci

    outputs:
      cache-dir: ${{ steps.npm-cache-dir.outputs.cache_dir }}
          
  test:
    name: Testing Job
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: npm cache directory
        run: |
          echo "Dir: ${{ needs.build.outputs.cache-dir }}"
      
      - name: Restore cache
        uses: actions/cache@v6
        with:
          key: ganesh-npm-cache
          path: ${{ needs.build.outputs.cache-dir }}

      - name: Install node modules
        run: cd node-app && npm ci

      - name: Run node app
        run: nohup npm start &

      - name: Smoke test
        run: curl http://localhost:3000/health
