name: Manually executed workflow
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Hostname
              run: 'echo "Hostname: $(hostname)"'
            - name: Uname
              run: |
                echo "Uname: $(uname -a)"
            - name: Listing all files
              run: ls -la
